// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Device struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	OperativeSystem string
	OsVersion       string
	Token           string
	Model           string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Task struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TaskID    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID         uuid.UUID
	Name       string
	Email      string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	FamilyName sql.NullString
	Picture    sql.NullString
}

type UserAuthProvider struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Provider       string
	ProviderUserID string
	AccessToken    sql.NullString
	RefreshToken   sql.NullString
	TokenExpiry    sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
